[workspace]
    members = [
        "p00_window", "p01_basic_triangle", "p02_uniform_buffer", "p03_geometry", "p04_textures", "p05_camera", "p06_obj",
        "p08_light",
        "testing",
    ]
    target-dir = "target"
