[package]
name = "p06_obj"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = {version = "=0.15.0", features = ["shader_format_glsl"]} 
bevy_obj = "0.15"
camera_plugin = { path = "../b01_camera_plugin" }
